# Generated by Django 4.0.4 on 2022-07-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='upload_to',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
